version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
  perl:
    build:
      context: ./perl
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react:
    extends:
      file: docker-compose-react.yml
      service: react
    depends_on:
      - perl
    links:
      - perl
    environment:
      API: http://perl:80
    ports:
      - "443:443"
