version: '2'
services:
  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql
  ruby_dev:
    build:
      context: ./ruby
      dockerfile: Dockerfile-dev
    volumes:
      - ./ruby:/app
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      ISUCON_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
  react:
    extends:
      file: docker-compose-react.yml
      service: react_dev
    depends_on:
      - ruby_dev
    links:
      - ruby_dev
    environment:
      API: http://ruby_dev:80
    ports:
      - "443:443"
