version: '2'
services:
  mysql:
    image: mysql
    volumes:
      - ./.data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
